### ISSUE TITLE
(Baturay) As external events, we would like to be handled properly

### ISSUE THREAD

**Issue by cagdasgerede** [tobbetu-ceng-industry-collaborations/smarteff-main#4] opened 2020-01-13 12:43 UTC
As a developer, I would like to implement a component that handles these types of events:

1) Event for a person entering and leaving the building
2) Event for a device getting turned on or off
3) Event for a person requesting the automated shutdowns to be suspended for a specifed time interval 
4) Event for requesting a device to be turned on / off

These should be modeled as HTTP POST messages with JSON bodies that contain the appropriate information. The details of these messages should be agreed on among all developers.

The component should provide API endpoints to be called over HTTP.

# Person enters
First, when a person enters the building, the data model should be updated to have the person's status to say the person is at the work place.

```
curl -d '{"personid":"123", "event":"entry"}' -H "Content-Type: application/json" -X POST http://hostname/HandlePersonEvent
```

# Device on/off
Similarly, when a device is turned on or off, the data model should be updated to have the correct device status.

```
curl -d '{"deviceid":"123", "event":"turnon"}' -H "Content-Type: application/json" -X POST http://hostname/HandleDeviceEvent

curl -d '{"deviceid":"123", "event":"turnoff"}' -H "Content-Type: application/json" -X POST http://hostname/HandleDeviceEvent

```

# Person leaves
Second, when a person leaves the building, the component should analyze what devices are no longer needed to be on. 

curl -d '{"personid":"123", "event":"exit"}' -H "Content-Type: application/json" -X POST http://hostname/HandlePersonEvent

A query like this can compute the active devices that are used by the user:

```
SELECT DeviceId
FROM PersonDevice NATURAL JOIN Person NATURAL JOIN Device
WHERE Person.PersonId = 3 AND Device.DeviceIsOn = 1
```

Then, we can find the devices that are not used by any user that is in the work place:

```
SELECT Device.DeviceId
FROM Device NATURAL JOIN PersonDevice NATURAL JOIN Person
WHERE
	Device.DeviceId IN (
		SELECT DeviceId
		FROM PersonDevice NATURAL JOIN Person NATURAL JOIN Device
		WHERE Person.PersonId = 3 AND Device.DeviceIsOn = 1
		)
	AND Person.PersonId != 3
	AND Device.DeviceIsOn = 1
	AND Person.IsInside = 1
GROUP BY Device.DeviceId
```

These are the devices for which all the users who use them already left the building.

The component then should fire a scheduled shutdown event for these devices. Another component implemented in #5 handles this event. Talk to the developer of #5 to agree on the details of the event format and the protocol - Most likely, it should be an http post with a json body which contains the device id and the timestamp of the shutdown request. To give some time for the workers to take action before their devices turned off, the actual shutdown can be processed in, for example, 5 minutes after the event is fired. The component in #5 will take care of this delayed processing.

# A device is requested to be kept of the automated shutdowns for a period of time
A person can request a device to be kept on for a time interval. This would prevent the automation to shutdown a device. When this event is received, a suspension entry should be created in the database. The suspension event that is received should contain the device id, person id, and the time interval for which the suspension is requested. 

## SuspendAutomation
An API endpoint to suspend the automated shutdown for a device for a time interval.

```
curl -d '{"DeviceId":"123", "PersonId":"3001", "Until": "20:00pm 20 January 2020"}' -H "Content-Type: application/json" -X POST http://hostname/SuspendAutomation
```

## EnableAutomation
An API endpoint to enable the automated shutdown for a device. This should clear out all the former suspension requests.

```
curl -d '{"DeviceId":"123", "PersonId":"3001"}' -H "Content-Type: application/json" -X POST http://hostname/EnableAutomation
```

# turn device on / off
The component should have the proper API endpoint to receive requests for a device to be turned on or turned off. The component should make the appropriate calls to the component implemented in #6 to delegate the actual action of turning a device on /off.

```
curl -d '{"PersonId": "8392", "DeviceId":"123", "Action":"turnon"}' -H "Content-Type: application/json" -X POST http://hostname/ManageDevice

curl -d '{"PersonId": "8392", "DeviceId":"123", "Action":"turnoff"}' -H "Content-Type: application/json" -X POST http://hostname/ManageDevice

```

**Comment by BaturayOnural** [comment] 2020-01-29 09:04
I am providing a table that contains the format of current HTTP calls of the API. Developers of the other components can rely on that this implementation will not change. HTTP calls for #7 will be represented in the table as well in the future.

[Smarteff REST API Calls.pdf](https://github.com/tobbetu-ceng-industry-collaborations/smarteff-main/files/4127008/Smarteff.REST.API.Calls.pdf)

**Comment by BaturayOnural** [comment] 2020-03-08 16:06
I am closing the issue since it has completely implemented as described. Feel free to write about any unexpected behavior of the API under this thread.

**Closed by BaturayOnural** 2020-03-08 16:06 UTC
Labels: student: baturay
